"""create referrals table

Revision ID: 2db4d19d4e1e
Revises: ba9f29384901
Create Date: 2024-10-25 16:10:06.177212

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2db4d19d4e1e"
down_revision: Union[str, None] = "ba9f29384901"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referrals",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("code_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["code_id"],
            ["referralcodes.id"],
            name=op.f("fk_referrals_code_id_referralcodes"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_referrals_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referrals")),
        sa.UniqueConstraint("user_id", name=op.f("uq_referrals_user_id")),
    )
    op.create_index(op.f("ix_referrals_id"), "referrals", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referrals_id"), table_name="referrals")
    op.drop_table("referrals")
    # ### end Alembic commands ###
