"""create referral code table

Revision ID: ba9f29384901
Revises: 202cbcc36d4a
Create Date: 2024-10-25 16:09:26.638126

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ba9f29384901"
down_revision: Union[str, None] = "202cbcc36d4a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referralcodes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author_id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("valid_until", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
            name=op.f("fk_referralcodes_author_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_referralcodes")),
        sa.UniqueConstraint(
            "author_id", name=op.f("uq_referralcodes_author_id")
        ),
    )
    op.create_index(
        op.f("ix_referralcodes_id"), "referralcodes", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_referralcodes_id"), table_name="referralcodes")
    op.drop_table("referralcodes")
    # ### end Alembic commands ###
